name: Rust Code Formatter (cargo fmt)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt (apply formatting)
        run: cargo fmt

      - name: Commit formatted code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --exit-code || (git commit -m "Format Rust code with cargo fmt" && git push)
        continue-on-error: true
